apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  labels:
    orchestrator-infra.redhat.com/chart-provisioned: "true"
spec:
  controller-custom-certs:
    name: ""
    type: ""
  registry: {}
