{{- if .Values.openshiftGitops.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: argocd-server
    app.kubernetes.io/name: {{ .Values.openshiftGitops.namespaces | first }}-gitops-argocd-server
    app.kubernetes.io/part-of: {{ .Values.openshiftGitops.namespaces | first }}
  name: {{ .Values.openshiftGitops.namespaces | first }}-gitops-argocd-server
rules:
  - apiGroups: [""]
    resources: ["pods", "logs"]
    verbs: ["get"]
{{- end }}
