{{- if and .Values.openshiftGitops.namespaces (.Capabilities.APIVersions.Has "argoproj.io/v1beta1/ArgoCD") }}
{{- range $ns := .Values.openshiftGitops.namespaces }}
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: {{ $.Values.openshiftGitops.name }}
  labels:
    app: {{ $.Values.openshiftGitops.name }}
  namespace: {{ $ns }}
spec:
  applicationInstanceLabelKey: rht-gitops.com/{{ $ns }}
  {{- if $.Values.openshiftGitops.argocd_cr }}
  {{- $.Values.openshiftGitops.argocd_cr | toYaml | trim | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
