{{- if .Values.openshiftGitops.namespaces }}
{{- range $ns := .Values.openshiftGitops.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: argocd-server
    app.kubernetes.io/name: {{ $ns }}-argocd-server
    app.kubernetes.io/part-of: {{ $ns }}
  name: {{ $ns }}-argocd-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $ns }}-gitops-argocd-server
subjects:
- kind: ServiceAccount
  name: {{ $.Values.openshiftGitops.name }}-argocd-server
  namespace: {{ $ns }}
{{- end }}
{{- end }}
