{{- if .Values.serverlessOperator.enabled }}
{{- $unmanagedNamespaceExists := include "unmanaged-resource-exists" (list "v1" "Namespace" "" "knative-serving" .Release.Name .Release.Namespace .Capabilities.APIVersions) }}
{{- if eq $unmanagedNamespaceExists "false" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
{{- end }}

{{- $unmanagedNamespaceExists := include "unmanaged-resource-exists" (list "v1" "Namespace" "" "knative-eventing" .Release.Name .Release.Namespace .Capabilities.APIVersions) }}
{{- if eq $unmanagedNamespaceExists "false" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
{{- end }}
{{- end }}
