orchestrator:
  enabled: true
  serverlessLogicOperator:
    enabled: true
  serverlessOperator:
    enabled: true
  sonataflowPlatform:
    monitoring:
      enabled: true
    eventing:
      broker:
        name: ""
        namespace: ""
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    # -- Secret name for the user-created secret to connect an external DB
    externalDBsecretRef: ""

    # -- Name for the user-configured external Database
    externalDBName: ""

    # -- Image for the init container used by the create-db job
    initContainerImage: busybox

    # -- Image for the container used by the create-db job
    createDBJobImage: "postgres:15"
