{{- if and .Values.serverlessLogicOperator.enabled (ne .Values.serverlessLogicOperator.subscription.namespace .Values.serverlessOperator.subscription.namespace) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.serverlessLogicOperator.subscription.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    "helm.sh/resource-policy": keep
{{- end }}
