nameOverride: developer-hub
global:
  dynamic:
    includes:
      - "dynamic-plugins.default.yaml"
    plugins: []
  clusterRouterBase: "apps.example.com"
  host: ""
  auth:
    backend:
      enabled: true
      existingSecret: ""
      value: ""
  catalogIndex:
    image:
      registry: quay.io
      repository: rhdh/plugin-catalog-index
      tag: "1.10"
    extraImages: []
  lightspeed:
    enabled: true
    plugins:
      - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-lightspeed:{{
          "{{inherit}}" }}'
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              red-hat-developer-hub.backstage-plugin-lightspeed:
                translationResources:
                  - importName: lightspeedTranslations
                    module: Alpha
                    ref: lightspeedTranslationRef
                dynamicRoutes:
                  - path: /lightspeed
                    importName: LightspeedPage
                mountPoints:
                  - mountPoint: application/listener
                    importName: LightspeedFAB
                  - mountPoint: application/provider
                    importName: LightspeedDrawerProvider
                  - mountPoint: application/internal/drawer-state
                    importName: LightspeedDrawerStateExposer
                    config:
                      id: lightspeed
                  - mountPoint: application/internal/drawer-content
                    importName: LightspeedChatContainer
                    config:
                      id: lightspeed
                      priority: 100
      - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-lightspeed-backend:{{
          "{{inherit}}" }}'
        disabled: false
    runtimeVolume:
      name: lightspeed-data
      mountPath: /tmp
      type: emptyDir
      emptyDir: {}
      persistentVolumeClaim: {}
    ragVolume:
      name: lightspeed-rag
      initMountPath: /rag-content
      mountPath: /rag-content
      emptyDir: {}
    configMaps:
      - name: stack
        create: true
        nameOverride: ""
        mountPath: /app-root/lightspeed-stack.yaml
        subPath: lightspeed-stack.yaml
        sourceFile: lightspeed-stack.yaml
        optional: false
      - name: config
        create: true
        nameOverride: ""
        mountPath: /app-root/config.yaml
        subPath: config.yaml
        sourceFile: config.yaml
        optional: false
      - name: rhdh-profile
        create: true
        nameOverride: ""
        mountPath: /app-root/rhdh-profile.py
        subPath: rhdh-profile.py
        sourceFile: rhdh-profile.py
        optional: false
    secret:
      create: true
      name: ""
      optional: false
      sourceFile: secret.yaml
    initContainer:
      name: lightspeed-rag-init
      image: quay.io/redhat-ai-dev/rag-content:release-1.9-lls-0.5.0-642c567fe10a62b5ff711654306b72912f341e05
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
      args:
        - >-
          mkdir -p /tmp/data && echo 'Copying Lightspeed RAG data...' && cp -r /rag/vector_db
          /rag-content/ && cp -r /rag/embeddings_model /rag-content/ && echo 'Copy
          complete.'
      env: []
      resources:
        requests:
          cpu: 50m
          memory: 150Mi
        limits:
          cpu: 100m
          memory: 500Mi
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"
    sidecar:
      name: lightspeed-core
      image: quay.io/lightspeed-core/lightspeed-stack:0.5.1
      imagePullPolicy: IfNotPresent
      portName: http-lightspeed
      containerPort: 8080
      command: []
      args: []
      env: []
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 2Gi
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"
upstream:
  nameOverride: developer-hub
  backstage:
    image:
      registry: quay.io
      repository: rhdh-community/rhdh
      tag: next-1.10
      pullPolicy: ""
    command: []
    appConfig:
      auth:
        providers: {}
      app:
        baseUrl: 'https://{{- include "rhdh.hostname" . }}'
      backend:
        baseUrl: 'https://{{- include "rhdh.hostname" . }}'
        cors:
          origin: 'https://{{- include "rhdh.hostname" . }}'
        database:
          connection:
            password: ${POSTGRESQL_ADMIN_PASSWORD}
            user: postgres
        auth:
          externalAccess:
            - type: legacy
              options:
                subject: legacy-default-config
                secret: ${BACKEND_SECRET}
    containerSecurityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      seccompProfile:
        type: "RuntimeDefault"
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2.5Gi
        ephemeral-storage: 5Gi
    startupProbe:
      httpGet:
        path: /.backstage/health/v1/liveness
        port: backend
        scheme: HTTP
      initialDelaySeconds: 30
      timeoutSeconds: 4
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /.backstage/health/v1/readiness
        port: backend
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 2
      timeoutSeconds: 4
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /.backstage/health/v1/liveness
        port: backend
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 4
    extraEnvVars:
      - name: BACKEND_SECRET
        valueFrom:
          secretKeyRef:
            key: backend-secret
            name: '{{ include "rhdh.backend-secret-name" $ }}'
      - name: POSTGRESQL_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            key: postgres-password
            name: '{{- include "rhdh.postgresql.secretName" . }}'
    args:
      - "--config"
      - dynamic-plugins-root/app-config.dynamic-plugins.yaml
    extraVolumeMounts:
      - name: dynamic-plugins-root
        mountPath: /opt/app-root/src/dynamic-plugins-root
      - name: extensions-catalog
        mountPath: /extensions
      - name: temp
        mountPath: /tmp
    extraVolumes:
      - name: dynamic-plugins-root
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
      - name: dynamic-plugins
        configMap:
          defaultMode: 420
          name: '{{ printf "%s-dynamic-plugins" .Release.Name }}'
          optional: true
      - name: dynamic-plugins-npmrc
        secret:
          defaultMode: 420
          optional: true
          secretName: '{{ printf "%s-dynamic-plugins-npmrc" .Release.Name }}'
      - name: dynamic-plugins-registry-auth
        secret:
          defaultMode: 416
          optional: true
          secretName: '{{ printf "%s-dynamic-plugins-registry-auth" .Release.Name
            }}'
      - name: npmcacache
        emptyDir: {}
      - name: extensions-catalog
        emptyDir: {}
      - name: temp
        emptyDir: {}
    initContainers:
      - name: install-dynamic-plugins
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 2.5Gi
            ephemeral-storage: 5Gi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: "RuntimeDefault"
        image: '{{ include "backstage.image" . }}'
        command:
          - ./install-dynamic-plugins.sh
          - /dynamic-plugins-root
        env:
          - name: NPM_CONFIG_USERCONFIG
            value: /opt/app-root/src/.npmrc.dynamic-plugins
          - name: MAX_ENTRY_SIZE
            value: "40000000"
          - name: CATALOG_INDEX_IMAGE
            value: '{{ .Values.global.catalogIndex.image.registry }}/{{ .Values.global.catalogIndex.image.repository
              }}:{{ .Values.global.catalogIndex.image.tag }}'
          - name: CATALOG_ENTITIES_EXTRACT_DIR
            value: '/extensions'
        imagePullPolicy: ""
        volumeMounts:
          - mountPath: /dynamic-plugins-root
            name: dynamic-plugins-root
          - mountPath: /opt/app-root/src/dynamic-plugins.yaml
            name: dynamic-plugins
            readOnly: true
            subPath: dynamic-plugins.yaml
          - mountPath: /opt/app-root/src/.npmrc.dynamic-plugins
            name: dynamic-plugins-npmrc
            readOnly: true
            subPath: .npmrc
          - mountPath: /opt/app-root/src/.config/containers
            name: dynamic-plugins-registry-auth
            readOnly: true
          - mountPath: /opt/app-root/src/.npm/_cacache
            name: npmcacache
          - name: extensions-catalog
            mountPath: /extensions
          - name: temp
            mountPath: /tmp
        workingDir: /opt/app-root/src
    installDir: /opt/app-root/src
  ingress:
    host: "{{ .Values.global.host }}"
  metrics:
    serviceMonitor:
      enabled: false
      path: /metrics
      port: http-metrics
  postgresql:
    enabled: true
    postgresqlDataDir: /var/lib/pgsql/data/userdata
    serviceBindings:
      enabled: true
    image:
      registry: quay.io
      repository: fedora/postgresql-15
      tag: latest
    auth:
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: password
    primary:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 1024Mi
          ephemeral-storage: 20Mi
      persistence:
        enabled: true
        size: 1Gi
        mountPath: /var/lib/pgsql/data
      extraEnvVars:
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: '{{- include "postgresql.v1.secretName" . }}'
  service:
    extraPorts:
      - name: http-metrics
        port: 9464
        targetPort: 9464
route:
  annotations: {}
  enabled: true
  host: "{{ .Values.global.host }}"
  path: "/"
  wildcardPolicy: None
  tls:
    enabled: true
    termination: "edge"
    certificate: ""
    key: ""
    caCertificate: ""
    destinationCACertificate: ""
    insecureEdgeTerminationPolicy: "Redirect"
test:
  enabled: true
  image:
    registry: quay.io
    repository: curl/curl
    tag: latest
  injectTestNpmrcSecret: false
orchestrator:
  enabled: false
  serverlessLogicOperator:
    enabled: true
  serverlessOperator:
    enabled: true
  sonataflowPlatform:
    monitoring:
      enabled: true
    eventing:
      broker:
        name: ""
        namespace: ""
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    externalDBsecretRef: ""
    externalDBName: ""
    externalDBHost: ""
    externalDBPort: ""
    initContainerImage: "{{ .Values.upstream.postgresql.image.registry }}/{{ .Values.upstream.postgresql.image.repository\
      \ }}:{{ .Values.upstream.postgresql.image.tag }}"
    createDBJobImage: "{{ .Values.upstream.postgresql.image.registry }}/{{ .Values.upstream.postgresql.image.repository\
      \ }}:{{ .Values.upstream.postgresql.image.tag }}"
    jobServiceImage: ""
    dataIndexImage: ""
  plugins:
    - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend:{{
        "{{inherit}}" }}'
      disabled: false
    - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets:{{
        "{{inherit}}" }}'
      disabled: false
    - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator:{{
        "{{inherit}}" }}'
      disabled: false
    - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator:{{
        "{{inherit}}" }}'
      disabled: false
