apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-dynamic-plugins" .Release.Name }}
data:
  dynamic-plugins.yaml: |
    {{- $dynamic := deepCopy .Values.global.dynamic }}
    {{- $plugins := list }}

    {{- range .Values.global.dynamic.plugins }}
      {{- $plugins = append $plugins . }}
    {{- end }}

    {{- if .Values.orchestrator.enabled }}
      {{- $orchestratorPlugins := include "orchestrator.plugins" . | fromYaml }}
      {{- range $orchestratorPlugins.plugins }}
        {{- $plugins = append $plugins . }}
      {{- end }}
    {{- end }}

    {{- $_ := set $dynamic "plugins" $plugins }}

    {{- include "common.tplvalues.render" (dict "value" $dynamic "context" $) | nindent 4 }}
---
{{- if .Values.orchestrator.enabled }}
  {{- $secretName := printf "%s-dynamic-plugins-npmrc" .Release.Name }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
  {{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  .npmrc: |
    @redhat:registry=https://npm.registry.redhat.com
  {{- end }}
{{- end }}
