apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-dynamic-plugins" .Release.Name }}
data:
  dynamic-plugins.yaml: |
    {{- include "common.tplvalues.render" ( dict "value"
    .Values.global.dynamic "context" $) | nindent 4 }}
