kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-audit-log" .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-dynamic-plugins-root" .Release.Name }}
spec:
  {{- toYaml .Values.dynamicPlugins.cache.volumeClaimSpec | nindent 2 }}
