name: SNYK

on:
  workflow_dispatch:  # allow manual runs from UI
  schedule:
    - cron: "0 0 * * 0"  # weekly scan (every Sunday at 00:00 UTC)

jobs:
  scan-iac:
    name: Scan Rendered Templates (${{ matrix.chartConfig.name }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        chartConfig:
          - name: "backstage"
            path: "backstage"
          - name: "orchestrator-infra"
            path: "orchestrator-infra"
          - name: "backstage-orchestrator"
            path: "backstage"
            cliArgs: "--set orchestrator.enabled=true"

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.17.0

      - name: Render Templates for ${{ matrix.chartConfig.name }}
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add backstage https://backstage.github.io/charts
          helm repo update

          helm dependency build ./charts/${{ matrix.chartConfig.path }}
          helm template ./charts/${{ matrix.chartConfig.path }} \
            ${{ matrix.chartConfig.cliArgs || '' }} \
            --output-dir ./output/${{ matrix.chartConfig.name }}

      - name: Run Snyk IaC Scan for ${{ matrix.chartConfig.name }}
        continue-on-error: true
        uses: snyk/actions/iac@b98d498629f1c368650224d6d212bf7dfa89e4bf # 0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
        with:
          args: --report --org=$SNYK_ORG_ID --target-name="redhat-developer/rhdh-chart/${{ matrix.chartConfig.name }}"
          file: ./output/${{ matrix.chartConfig.name }}
