name: Test Charts

on:
  pull_request:
    branches:
      - main
      - rhdh-1.[0-9]+
      - 1.[0-9]+.x
      - release-1.[0-9]+
    paths:
      - "charts/**"
      - ".github/**"
      - ".pre-commit/**"
      - "ct-install.yaml"
      - "ct.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  check-metadata:
    name: Lint Metadata
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: 3.13

      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: ^1

      - name: Setup helm-docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: --show-diff-on-failure

  test-chart:
    strategy:
      matrix:
        version:
          # 'latest' is the latest RC or stable release of RHDH (built from a release branch)
          - latest
        experimental: [false]
        include:
          # 'next' is the upcoming release of RHDH
          # (built from the RHDH main branch, so might be unstable)
          - version: next
            experimental: true

    name: Test ${{ matrix.version }} release
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # renovate: tag=v3.5
        with:
          version: v3.10.0

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: 3.13

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: "Add required Helm repositories"
        run: |
          helm repo add bitnami "https://charts.bitnami.com/bitnami"
          helm repo add backstage https://backstage.github.io/charts
          helm repo update

      - name: Lint chart
        run: |
          ct lint \
            --debug \
            --config ct.yaml \
            --target-branch "${{ github.event.pull_request.base.ref }}" \
            --helm-extra-args="--set upstream.backstage.image.tag=${{ matrix.version }} --set ingress.enabled=true"

      - name: Start Minikube
        uses: medyagh/setup-minikube@cea33675329b799adccc9526aa5daccc26cd5052 # v0.0.19
        with:
          addons: ingress

      - name: Create custom storage class
        run: |
          export defaultScProvisioner=$(kubectl get storageclass -o jsonpath='{.items[?(@.metadata.annotations.storageclass\.kubernetes\.io/is-default-class=="true")].provisioner}')
          if [[ -z "$defaultScProvisioner" ]]; then
            echo "No default storage class found or it has no provisioner. Exiting early because the test using the custom Storage Class will likely fail. Use a cluster that has a default storage class."
            exit 1
          fi
          cat <<EOF | kubectl apply -f -
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: custom-sc
          # same provisioner as the one used by the default storage class on the cluster
          provisioner: "$defaultScProvisioner"
          reclaimPolicy: Delete
          volumeBindingMode: WaitForFirstConsumer
          EOF

      - name: Install Operator Lifecycle Manager (OLM)
        # In case we need to install additional Operators
        env:
          OLM_VERSION: "v0.31.0"
        run: |
          curl -L "https://github.com/operator-framework/operator-lifecycle-manager/releases/download/${OLM_VERSION}/install.sh" -o install-olm.sh
          chmod +x install-olm.sh
          ./install-olm.sh "${OLM_VERSION}"

      - name: Build Ingress Domain
        run: |
          echo "K8S_INGRESS_DOMAIN=$(minikube ip).sslip.io" >> $GITHUB_ENV

      - name: Run chart-testing
        env:
          INGRESS_HOST: "rhdh.${{ env.K8S_INGRESS_DOMAIN }}"
        run: |
          ct install \
            --debug \
            --config ct-install.yaml \
            --upgrade \
            --target-branch "${{ github.event.pull_request.base.ref }}" \
            --helm-extra-set-args="--set upstream.backstage.image.tag=${{ matrix.version }} --set ingress.enabled=true --set global.host=${INGRESS_HOST}"
